image: node:6

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_HMG
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_HMG
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_HMG
          - export S3_BUCKET=$S3_BUCKET_HMG
          - export APPLICATION_NAME=$APPLICATION_NAME_HMG
          - export DEPLOYMENT_CONFIG=$DEPLOYMENT_CONFIG_HMG
          - export DEPLOYMENT_GROUP_NAME=$DEPLOYMENT_GROUP_NAME_HMG
          - npm install
          - npm test
          - npm run build
          - npm prune --production
          - apt-get update
          - apt-get install -y zip python-pip python-dev build-essential
          - pip install boto3==1.3.0
          - zip -r /tmp/artifact.zip .
          - python codedeploy_deploy.py

  branches:
    master:
      - step:
          caches:
            - node
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRD
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRD
            - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PRD
            - export S3_BUCKET=$S3_BUCKET_PRD            
            - export APPLICATION_NAME=$APPLICATION_NAME_PRD
            - export DEPLOYMENT_CONFIG=$DEPLOYMENT_CONFIG_PRD
            - export DEPLOYMENT_GROUP_NAME=$DEPLOYMENT_GROUP_NAME_PRD
            - npm install
            - npm test
            - npm run build
            - npm prune --production
            - apt-get update
            - apt-get install -y zip python-pip python-dev build-essential curl
            - pip install boto3==1.3.0
            - zip -r /tmp/artifact.zip .
            - python codedeploy_deploy.py
            - curl https://s3.amazonaws.com/maxmilhas/shell/notify.sh | bash -
