version: '2'
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      - my-network
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - my-network
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'pass123'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
